/**
 * Snapshot baseline — capture current violations and only fail on regressions.
 *
 * Violation identity uses `ruleId + stableSelector` where the selector is
 * generated by Playwright's own InjectedScript.generateSelectorSimple(),
 * producing role-based / semantic selectors (e.g. `getByRole('img')`) that
 * are resilient to class-name and ID churn.
 */
import { createRequire } from "node:module";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Page, Locator } from "@playwright/test";
import type { AuditViolation } from "./audit";

const require = createRequire(import.meta.url);

export interface SnapshotViolation {
  ruleId: string;
  selector: string;
}

export interface SnapshotResult {
  pass: boolean;
  newViolations: SnapshotViolation[];
  fixedViolations: SnapshotViolation[];
  updated: boolean;
  created: boolean;
}

// ---------------------------------------------------------------------------
// Name validation
// ---------------------------------------------------------------------------

export function validateSnapshotName(name: string): void {
  if (!name || typeof name !== "string") {
    throw new Error("Snapshot name must be a non-empty string");
  }
  if (/[/\\:*?"<>|]/.test(name)) {
    throw new Error(
      `Snapshot name "${name}" contains invalid characters ` +
        `(path separators and special characters are not allowed)`,
    );
  }
}

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

export function resolveSnapshotPath(name: string, dir?: string): string {
  validateSnapshotName(name);
  const base = dir || resolve(process.cwd(), "accessibility-snapshots");
  return resolve(base, `${name}.json`);
}

// ---------------------------------------------------------------------------
// File I/O
// ---------------------------------------------------------------------------

export function loadSnapshot(path: string): SnapshotViolation[] | null {
  try {
    const data = readFileSync(path, "utf-8");
    return JSON.parse(data);
  } catch {
    return null;
  }
}

export function saveSnapshot(
  path: string,
  violations: SnapshotViolation[],
): void {
  const sorted = [...violations].sort(
    (a, b) =>
      a.ruleId.localeCompare(b.ruleId) ||
      a.selector.localeCompare(b.selector),
  );
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(sorted, null, 2) + "\n");
}

// ---------------------------------------------------------------------------
// Comparison
// ---------------------------------------------------------------------------

function violationKey(v: SnapshotViolation): string {
  return `${v.ruleId}\0${v.selector}`;
}

export function compareViolations(
  current: SnapshotViolation[],
  baseline: SnapshotViolation[],
): { newViolations: SnapshotViolation[]; fixedViolations: SnapshotViolation[] } {
  const baselineSet = new Set(baseline.map(violationKey));
  const currentSet = new Set(current.map(violationKey));

  return {
    newViolations: current.filter((v) => !baselineSet.has(violationKey(v))),
    fixedViolations: baseline.filter((v) => !currentSet.has(violationKey(v))),
  };
}

// ---------------------------------------------------------------------------
// Evaluate snapshot (create / compare / ratchet / update)
// ---------------------------------------------------------------------------

export function evaluateSnapshot(
  currentViolations: SnapshotViolation[],
  snapshotPath: string,
  options?: { update?: boolean },
): SnapshotResult {
  const update = options?.update ?? false;
  const baseline = loadSnapshot(snapshotPath);

  // No snapshot file → create it, test passes
  if (baseline === null) {
    saveSnapshot(snapshotPath, currentViolations);
    return {
      pass: true,
      newViolations: [],
      fixedViolations: [],
      updated: false,
      created: true,
    };
  }

  // Force update (ACCESSLINT_UPDATE=1 or playwright test -u)
  if (update) {
    saveSnapshot(snapshotPath, currentViolations);
    return {
      pass: true,
      newViolations: [],
      fixedViolations: [],
      updated: true,
      created: false,
    };
  }

  const { newViolations, fixedViolations } = compareViolations(
    currentViolations,
    baseline,
  );

  // Ratchet down — auto-update when violations only decreased
  if (newViolations.length === 0 && fixedViolations.length > 0) {
    saveSnapshot(snapshotPath, currentViolations);
  }

  return {
    pass: newViolations.length === 0,
    newViolations,
    fixedViolations,
    updated: fixedViolations.length > 0 && newViolations.length === 0,
    created: false,
  };
}

// ---------------------------------------------------------------------------
// Page settle heuristic
// ---------------------------------------------------------------------------

function getPage(target: Page | Locator): Page {
  return typeof (target as Page).goto === "function"
    ? (target as Page)
    : (target as Locator).page();
}

/**
 * Wait for the page to reach a stable state before auditing.
 *
 * 1. Waits for `domcontentloaded`
 * 2. Waits for a 100 ms window with no DOM mutations (max 2 s)
 */
export async function waitForPageSettle(target: Page | Locator): Promise<void> {
  const page = getPage(target);

  await page.waitForLoadState("domcontentloaded").catch(() => {});

  await page
    .evaluate(
      () =>
        new Promise<void>((resolve) => {
          const maxWait = setTimeout(() => {
            observer.disconnect();
            resolve();
          }, 2_000);

          let quietTimer = setTimeout(() => {
            clearTimeout(maxWait);
            observer.disconnect();
            resolve();
          }, 100);

          const observer = new MutationObserver(() => {
            clearTimeout(quietTimer);
            quietTimer = setTimeout(() => {
              clearTimeout(maxWait);
              observer.disconnect();
              resolve();
            }, 100);
          });

          observer.observe(document, {
            childList: true,
            subtree: true,
            attributes: true,
          });
        }),
    )
    .catch(() => {});
}

// ---------------------------------------------------------------------------
// Stable selector generation via Playwright's InjectedScript + asLocator
// ---------------------------------------------------------------------------

/**
 * Resolve a private file path under playwright-core.
 * The package restricts its `exports` map, so we resolve relative to the
 * package root instead.
 */
function playwrightCorePath(subpath: string): string {
  const pkgJson = require.resolve("playwright-core/package.json");
  return resolve(dirname(pkgJson), subpath);
}

/** Read the InjectedScript source that Playwright injects into pages. */
function getInjectedScriptSource(): string {
  const filePath = playwrightCorePath(
    "lib/generated/injectedScriptSource.js",
  );
  const mod: { exports: { source: string } } = { exports: { source: "" } };
  const fn = new Function("module", "exports", readFileSync(filePath, "utf-8"));
  fn(mod, mod.exports);
  return mod.exports.source;
}

/** Convert a Playwright internal selector to a locator string. */
function loadAsLocator(): (lang: string, selector: string) => string {
  const filePath = playwrightCorePath(
    "lib/utils/isomorphic/locatorGenerators.js",
  );
  return require(filePath).asLocator;
}

let _injectedSource: string | undefined;
let _asLocator: ((lang: string, selector: string) => string) | undefined;

/** Inject Playwright's InjectedScript into the page (once per page). */
async function ensureInjectedScript(page: Page): Promise<void> {
  const done = await page.evaluate(
    () => typeof (window as any).__accesslintInjected !== "undefined",
  );
  if (done) return;

  if (!_injectedSource) _injectedSource = getInjectedScriptSource();

  await page.addScriptTag({
    content: `(() => {
      const module = {};
      ${_injectedSource}
      window.__accesslintInjected = new (module.exports.InjectedScript())(globalThis, {
        isUnderTest: false,
        sdkLanguage: 'javascript',
        testIdAttributeName: 'data-testid',
        stableRafCount: 1,
        browserName: 'chromium',
        isUtilityWorld: false,
        customEngines: [],
      });
    })();`,
  });
}

/**
 * Convert audit violations into snapshot violations with **stable selectors**.
 *
 * Uses Playwright's `InjectedScript.generateSelectorSimple()` — the same
 * engine behind codegen — to produce selectors that favor ARIA roles,
 * accessible names, text content, and test IDs over CSS classes and random
 * IDs.  The internal selector format is then converted to the human-readable
 * Locator API form via `asLocator()`.
 *
 * Example: `main > img`  →  `getByRole('img')`
 *
 * Falls back to a tag-path selector if injection fails.
 */
export async function toStableViolations(
  target: Page | Locator,
  violations: AuditViolation[],
): Promise<SnapshotViolation[]> {
  if (violations.length === 0) return [];

  const page = getPage(target);
  const selectors = violations.map((v) => v.selector);

  let stableSelectors: string[];
  try {
    await ensureInjectedScript(page);
    if (!_asLocator) _asLocator = loadAsLocator();
    const asLocator = _asLocator;

    const internalSelectors: string[] = await page.evaluate(
      (cssSelectors: string[]) => {
        const injected = (window as any).__accesslintInjected;

        return cssSelectors.map((selector) => {
          // Shadow-DOM / iframe boundary selectors — keep as-is
          if (selector.includes(">>>")) return selector;

          try {
            const el = selector
              ? document.querySelector(selector)
              : document.documentElement;
            if (!el) return selector;
            return injected.generateSelectorSimple(el, {
              testIdAttributeName: "data-testid",
            });
          } catch {
            return selector;
          }
        });
      },
      selectors,
    );

    // Convert internal:role=button[name="X"i] → getByRole('button', { name: 'X' })
    stableSelectors = internalSelectors.map((sel) => {
      if (sel.includes(">>>")) return sel;
      try {
        return asLocator("javascript", sel);
      } catch {
        return sel;
      }
    });
  } catch {
    // Fallback: tag-path selectors if InjectedScript fails
    stableSelectors = await tagPathFallback(page, selectors);
  }

  return violations.map((v, i) => ({
    ruleId: v.ruleId,
    selector: stableSelectors[i],
  }));
}

async function tagPathFallback(
  page: Page,
  selectors: string[],
): Promise<string[]> {
  return page.evaluate((cssSelectors: string[]) => {
    function tagPath(el: Element): string {
      const parts: string[] = [];
      let current: Element | null = el;
      while (current) {
        let tag = current.tagName.toLowerCase();
        const parent = current.parentElement;
        if (parent) {
          const siblings = Array.from(parent.children).filter(
            (c) => c.tagName === current!.tagName,
          );
          if (siblings.length > 1) {
            tag += `:nth-of-type(${siblings.indexOf(current) + 1})`;
          }
        }
        parts.unshift(tag);
        current = current.parentElement;
      }
      return parts.join(" > ");
    }

    return cssSelectors.map((selector) => {
      if (selector.includes(">>>")) return selector;
      try {
        const el = selector
          ? document.querySelector(selector)
          : document.documentElement;
        return el ? tagPath(el) : selector;
      } catch {
        return selector;
      }
    });
  }, selectors);
}
